---
# Extract data from pdb files.
#
#     $ ansible-playbook extract_pdb_data.yml -e puzzle_id=2003893
#
# To see a list of available puzzle ids, run the helper script first:
#
#     $ python scripts/list_available_puzzles.py

- hosts: analytics.fold.it
  remote_user: pierce
  vars:
    - python: ~/venv/bin/python
    - script: ~/foldit/scripts/parse_solution_pdb_files.py
  tasks:
    - name: Run parse solution pdb files
      shell: "{{ python }} {{ script }} {{ puzzle_id }}"
      # creates ~/data/parsed/{{ puzzle_id }}.csv

    - name: Copy results back to host machine
      fetch:
        src: "~/data/parsed/{{ puzzle_id }}.csv"
        dest: "../data/parsed/{{ puzzle_id }}.csv"
