---
# Search the analytics.fold.it server for available data files.
#
# Specify the type of data to search for as a command line variable
# to the Ansible Playbook.
#
#     $ ansible-playbook find_puzzles.yml -e 'type=all'
#     $ ansible-playbook find_puzzles.yml -e '{type: "top", rank: "bid", puzzle_id: 2003996}'
#     $ ansible-playbook find_puzzles.yml -e '@vars/sketchbook_puzzles.yml'

- hosts: analytics.fold.it
  remote_user: pierce
  tasks:
    - name: Make data dir on host
      local_action: command 'mkdir -p {{ data_dir | default("../data") }}'

    - include: tasks/find_puzzles_with_available_data.yml
      when: type == 'all'

    - include: tasks/find_puzzles_with_top_data.yml
      when: type == 'top'
