---
- hosts: analytics.fold.it
  remote_user: pierce
  vars_files:
    - vars/top.yml
  tasks:
    - name: Verify that the dest directory exists on src
      file: path=~/{{ dest }} state=directory

    - name: Find all puzzles with available data
      shell: 'find ~/fetch/ -maxdepth 1 -name "solution_*" -type d -exec find {}/top -maxdepth 1 -name "*.pdb" \; > ~/{{ available_solutions }}'

    - name: Verify that the dest directory exists on control
      local_action: file path={{ dest }} state=directory

    - name: Fetch the available solutions back to the control machine
      fetch: src=~/{{ available_solutions }} dest={{ available_solutions }} flat=yes
